dist: xenial
language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8-dev
    env: TOXENV=py38-dev
  - python: 3.7
    env: TOXENV=style
  - python: 3.7
    env: TOXENV=lint
  - python: 3.7
    env: TOXENV=type
  - python: 3.7
    env: TOXENV=security
  - python: 3.7
    env: TOXENV=pkg
install: pip install 'tox == 3.7.0'
script: tox --skip-missing-interpreters false
